spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: dbcp1
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.100:3306/auth_test?autoReconnect=true&useSSL=false
    username: ${AUTH_DB_PWD:simu}
    password: ${AUTH_DB_USER:simu123}
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    database: 0
    host: ${REDIS_ADDRESS:192.168.1.204}
    password: ${REDIS_PWD:Superid123}
    timeout: 3000
    pool:
      max-active: 8
      min-idle: 0
      max-wait: -1
      max-idle: 8

ribbon:
  ReadTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000

